//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [UBYTE(0x3)][0x6],1 [UBYTE(0x3)][0x7],2 [BBOOL(0x19)][0x10],3 [UBYTE(0x3)][0x8],4 [UBYTE(0x3)][0x9],5 [UBYTE(0x3)][0xa],6 [STRING(0x0)][0x0],7 [UBYTE(0x3)][0xb],8 [UBYTE(0x3)][0xc],9 [UBYTE(0x3)][0xd],10 [UBYTE(0x3)][0xe],11 [UBYTE(0x3)][0xf],12 [USHORT(0x5)][0x4],13 [BBOOL(0x1a)][0x10],14 [BBOOL(0x1b)][0x10],15 [BBOOL(0x1c)][0x10],16 [BBOOL(0x1d)][0x10],17 [BBOOL(0x1e)][0x10]
        ///0,0,1,false,0,0,0,&quot;&quot;,0,0,0,0,0,0,false,false,true,false,true
        ///1,0,1,false,0,1,0,&quot;normal/Battle Start&quot;,0,0,0,2,3,0,false,fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string actiontimeline {
            get {
                return ResourceManager.GetString("actiontimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [INT(0x6)][0x8],3 [INT(0x6)][0x10],4 [INT(0x6)][0x18],5 [INT(0x6)][0x20],6 [INT(0x6)][0xc],7 [INT(0x6)][0x14],8 [INT(0x6)][0x1c],9 [INT(0x6)][0x24]
        ///0,&quot;None&quot;,&quot;None&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Hyur&quot;,&quot;Hyur&quot;,2983,3520,3296,3750,2984,3521,3297,3751
        ///2,&quot;Elezen&quot;,&quot;Elezen&quot;,2985,3522,3298,3752,2986,3523,3299,3753
        ///3,&quot;Lalafell&quot;,&quot;Lalafell&quot;,2987,3524,3300,3754,2988,3525,3301,3755
        ///4,&quot;Miqo&apos;te&quot;,&quot;Miqo&apos;te&quot;,2989,3526,3302,3756,2990,3527,3303,3757
        ///5,&quot;Roegadyn&quot;,&quot;Roegadyn&quot;,2991,3528, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string raceEN {
            get {
                return ResourceManager.GetString("raceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x4],2 [BYTE(0x2)][0x8],3 [BYTE(0x2)][0x9],4 [BYTE(0x2)][0xa],5 [BYTE(0x2)][0xb],6 [BYTE(0x2)][0xc],7 [BYTE(0x2)][0xd],8 [BYTE(0x2)][0xe],9 [BYTE(0x2)][0xf]
        ///0,&quot;None&quot;,&quot;None&quot;,0,0,0,0,0,0,0,0
        ///1,&quot;Midlander&quot;,&quot;Midlander&quot;,0,0,2,0,-1,3,-1,0
        ///2,&quot;Highlander&quot;,&quot;Highlander&quot;,0,0,3,2,0,-2,0,0
        ///3,&quot;Wildwood&quot;,&quot;Wildwood&quot;,0,0,0,-1,3,2,-1,0
        ///4,&quot;Duskwight&quot;,&quot;Duskwight&quot;,0,0,0,-1,0,3,1,0
        ///5,&quot;Plainsfolk&quot;,&quot;Plainsfolk&quot;,0,0,-1,-1,3,2,0,0
        ///6,&quot;Dunesfolk&quot;,&quot;Dunesfolk&quot;,0,0,-1,-2,1,2,3,0
        ///7,&quot;Seeke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tribe_exh_en {
            get {
                return ResourceManager.GetString("tribe_exh_en", resourceCulture);
            }
        }
    }
}
